spring.application.name=product-api

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:mysql://localhost:3306/product?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Desativa Flyway no perfil default para usar H2 em memória
spring.flyway.enabled=false

# JWT Configuration
app.jwt.secret=mySecretKeyForJWT2024ProductAPIWithMinimum256BitsForHS256AlgorithmSecurity
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000

# Server Configuration
server.port=8080
