spring.application.name=

 
spring.h2.console.enabled=
spring.h2.console.path=

 spring.datasource.url=
spring.datasource.driverClassName=
spring.datasource.username=
spring.datasource.password=

 spring.jpa.show-sql=
spring.jpa.hibernate.ddl-auto=
spring.jpa.properties.hibernate.format_sql=

 app.jwt.secret=
app.jwt.expiration-ms=

 server.port=
