spring.application.name=product-api

# MySQL datasource (padrão em runtime)
spring.datasource.url=jdbc:mysql://localhost:3306/productdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=product
spring.datasource.password=product
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false

# Flyway para MySQL
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
app.jwt.secret=changeit-super-secret-key-please-changeme
app.jwt.expiration-ms=86400000

# Erros enxutos
server.error.include-stacktrace=never
server.error.include-message=always
